In [ ]:
 
 import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [19]:
from os import name
df = pd.read_csv('/content/drive/MyDrive/Machine Learning/NLP/train.txt',sep=';',header=None,names=['text','emotion'])

In [20]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [21]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [22]:
unique = df['emotion'].unique()
dictionary={}
i=0
for u in unique:
  dictionary[u]=i
  i+=1

dictionary

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [23]:
df['emotion']=df['emotion'].map(dictionary)

In [24]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [25]:
# sabse small function likhna ho to that is lambda function

# we are currently doint text cleaning

In [26]:
import string

def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [27]:
df['text']=df['text'].apply(remove_punc)

In [28]:
import re

def remove_numbers(text):
  return re.sub(r'\d+', '', text)

In [29]:
# code to remove emojis

import re

def remove_emojis(text):
    emoji_pattern = re.compile(
        "["
        "\U0001F600-\U0001F64F"
        "\U0001F300-\U0001F5FF"
        "\U0001F680-\U0001F6FF"
        "\U0001F1E0-\U0001F1FF"
        "\U00002702-\U000027B0"
        "\U000024C2-\U0001F251"
        "]+"
    )
    return emoji_pattern.sub(r'', text)

In [30]:
df['text'] = df['text'].apply(remove_emojis)

In [31]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [32]:
df['text'] = df['text'].apply(remove_numbers)

In [33]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [34]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In machine learning, a corpus simply means a large, structured collection of data, usually text, that is used to train, test, or evaluate models.

In [35]:
nltk.download('stopwords')
nltk.download('punkt')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [36]:
pip uninstall nltk -y

Found existing installation: nltk 3.9.4
Uninstalling nltk-3.9.4:
  Successfully uninstalled nltk-3.9.4

In [37]:
pip install nltk

Collecting nltk
  Using cached nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Using cached nltk-3.9.4-py3-none-any.whl (1.6 MB)
Installing collected packages: nltk
Successfully installed nltk-3.9.4

In [38]:
import nltk
print(f"NLTK version: {nltk.__version__}")
nltk.download('stopwords')
nltk.download('punkt')

NLTK version: 3.9.4

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [39]:
stop_words=set(stopwords.words('english'))

In [2]:
import pandas as pd
try:
    df = pd.read_csv('/content/drive/MyDrive/Machine Learning/NLP/train.txt', sep=';', header=None, names=['text','emotion'])
    print('Dataframe loaded successfully.')
    display(df.head())
except Exception as e:
    print(f'Error loading file: {e}')

Dataframe loaded successfully.

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [3]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [14]:
def remove_stopward(txt):
    words = split(txt)

    cleaned = [i for i in words if i.lower() not in stop_words]
    return ' '.join(cleaned)

In [17]:
df['text']=df['text'].apply(remove_stopward)

NameError: name 'split' is not defined

In [ ]:
# this will make sure that the text is now clean